"""Add new columns to track progress

Revision ID: 4b0f178ab657
Revises: 
Create Date: 2025-04-21 20:07:54.142263

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4b0f178ab657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('flash_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'times_seen',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))
        batch_op.add_column(sa.Column(
            'times_wrong',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))
        batch_op.add_column(sa.Column(
            'ease', sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_cards', schema=None) as batch_op:
        batch_op.drop_column('ease')
        batch_op.drop_column('times_wrong')
        batch_op.drop_column('times_seen')

    # ### end Alembic commands ###
