"""Add correct flashcard column

Revision ID: b631d6533618
Revises: 4b0f178ab657
Create Date: 2025-04-21 22:07:08.065404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b631d6533618'
down_revision = '4b0f178ab657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'times_correct',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_cards', schema=None) as batch_op:
        batch_op.drop_column('times_correct')

    # ### end Alembic commands ###
